// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/account": {
            "get": {
                "security": [
                    {
                        "access_token": []
                    }
                ],
                "tags": [
                    "Account"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/account_usecase.AuthOutput"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httphelper.HttpError"
                        }
                    }
                }
            },
            "patch": {
                "tags": [
                    "Account"
                ],
                "parameters": [
                    {
                        "description": "update input data",
                        "name": "customer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/account_handler.updateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httphelper.HttpError"
                        }
                    }
                }
            }
        },
        "/account/login": {
            "post": {
                "tags": [
                    "Account"
                ],
                "parameters": [
                    {
                        "description": "login input data",
                        "name": "customer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/account_handler.loginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/account_usecase.AuthOutput"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httphelper.HttpError"
                        }
                    }
                }
            }
        },
        "/account/logout": {
            "post": {
                "security": [
                    {
                        "access_token": []
                    }
                ],
                "tags": [
                    "Account"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/account/password": {
            "patch": {
                "tags": [
                    "Account"
                ],
                "parameters": [
                    {
                        "description": "change password data",
                        "name": "customer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/account_handler.changePasswordReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/account_usecase.AuthOutput"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httphelper.HttpError"
                        }
                    }
                }
            }
        },
        "/projects": {
            "get": {
                "security": [
                    {
                        "access_token": []
                    }
                ],
                "tags": [
                    "Projects"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/project_usecase.ProjectOutput"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httphelper.HttpError"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "Projects"
                ],
                "parameters": [
                    {
                        "description": "add project data",
                        "name": "project",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/projects_handler.addReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httphelper.HttpError"
                        }
                    }
                }
            }
        },
        "/projects/{projectID}": {
            "delete": {
                "tags": [
                    "Projects"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "projectID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httphelper.HttpError"
                        }
                    }
                }
            },
            "patch": {
                "tags": [
                    "Projects"
                ],
                "parameters": [
                    {
                        "description": "update project body",
                        "name": "project",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/projects_handler.updateReq"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "projectID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httphelper.HttpError"
                        }
                    }
                }
            }
        },
        "/projects/{projectID}/menu/category": {
            "post": {
                "tags": [
                    "Menu"
                ],
                "parameters": [
                    {
                        "description": "body data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/menu_handler.addCategoryReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httphelper.HttpError"
                        }
                    }
                }
            }
        },
        "/projects/{projectID}/menu/category/{categoryID}": {
            "delete": {
                "tags": [
                    "Menu"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httphelper.HttpError"
                        }
                    }
                }
            },
            "patch": {
                "tags": [
                    "Menu"
                ],
                "parameters": [
                    {
                        "description": "body data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/menu_handler.updateCategoryReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httphelper.HttpError"
                        }
                    }
                }
            }
        },
        "/projects/{projectID}/menu/category/{categoryID}/positions": {
            "patch": {
                "tags": [
                    "Menu"
                ],
                "parameters": [
                    {
                        "description": "body data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/menu_handler.updateCategoryPositionReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httphelper.HttpError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "account_handler.changePasswordReq": {
            "type": "object",
            "required": [
                "new_password",
                "old_password"
            ],
            "properties": {
                "clear_session": {
                    "type": "boolean",
                    "example": false
                },
                "new_password": {
                    "type": "string",
                    "example": "QcU+,317QL[t"
                },
                "old_password": {
                    "type": "string",
                    "example": "badboy2015"
                }
            }
        },
        "account_handler.loginReq": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "qwerty123"
                }
            }
        },
        "account_handler.updateReq": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "John Doe"
                }
            }
        },
        "account_usecase.AuthOutput": {
            "type": "object",
            "properties": {
                "customer": {
                    "$ref": "#/definitions/account_usecase.Customer"
                },
                "subscription": {
                    "$ref": "#/definitions/account_usecase.Subscription"
                }
            }
        },
        "account_usecase.Customer": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "account_usecase.Subscription": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                }
            }
        },
        "httphelper.HttpError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                }
            }
        },
        "menu_handler.AddInputTr": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "menu_handler.addCategoryReq": {
            "type": "object",
            "required": [
                "position",
                "project_id",
                "translations"
            ],
            "properties": {
                "position": {
                    "type": "integer"
                },
                "project_id": {
                    "type": "string"
                },
                "translations": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/menu_handler.AddInputTr"
                    }
                }
            }
        },
        "menu_handler.updateCategoryPositionReq": {
            "type": "object",
            "required": [
                "categories"
            ],
            "properties": {
                "categories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/menu_handler.updateCategoryPositionReqItem"
                    }
                }
            }
        },
        "menu_handler.updateCategoryPositionReqItem": {
            "type": "object",
            "required": [
                "id",
                "position"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "position": {
                    "type": "integer"
                }
            }
        },
        "menu_handler.updateCategoryReq": {
            "type": "object",
            "required": [
                "translations"
            ],
            "properties": {
                "translations": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/menu_handler.updateCategoryTr"
                    }
                }
            }
        },
        "menu_handler.updateCategoryTr": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "project_usecase.ProjectOutput": {
            "type": "object",
            "properties": {
                "background_url": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "languages": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "logo_url": {
                    "type": "string"
                },
                "modules": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/project_usecase.ProjectOutputModule"
                    }
                },
                "name": {
                    "type": "string"
                },
                "service_fee": {
                    "type": "integer"
                },
                "translations": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/project_usecase.ProjectOutputTranslation"
                    }
                }
            }
        },
        "project_usecase.ProjectOutputModule": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "module_id": {
                    "type": "string"
                },
                "options": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/project_usecase.ProjectOutputOption"
                    }
                }
            }
        },
        "project_usecase.ProjectOutputOption": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "option_id": {
                    "type": "string"
                },
                "params": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/project_usecase.ProjectOutputParam"
                    }
                }
            }
        },
        "project_usecase.ProjectOutputParam": {
            "type": "object",
            "properties": {
                "param_id": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "project_usecase.ProjectOutputTranslation": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                }
            }
        },
        "projects_handler.addReq": {
            "type": "object",
            "required": [
                "background",
                "description",
                "languages",
                "logo",
                "name",
                "service_fee"
            ],
            "properties": {
                "background": {
                    "type": "string",
                    "example": "aGVsbG8gd29ybGQ="
                },
                "description": {
                    "type": "string",
                    "example": "The Best Restaurant in the City."
                },
                "languages": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "kz",
                        "en"
                    ]
                },
                "logo": {
                    "type": "string",
                    "example": "aGVsbG8gd29ybGQ="
                },
                "name": {
                    "type": "string",
                    "example": "Burger Queen"
                },
                "service_fee": {
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "projects_handler.updateReq": {
            "type": "object",
            "required": [
                "languages",
                "name",
                "service_fee",
                "translations"
            ],
            "properties": {
                "languages": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "service_fee": {
                    "type": "integer"
                },
                "translations": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/projects_handler.updateReqTranslation"
                    }
                }
            }
        },
        "projects_handler.updateReqTranslation": {
            "type": "object",
            "required": [
                "description"
            ],
            "properties": {
                "description": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Foodx API Documentation",
	Description:      "no description",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
